pipeline:
  identifier: GoLangPipeline
  name: GoLangPipeline
  orgIdentifier: WiproPOC
  projectIdentifier: GoLangPipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695291009490
        repoName: deenaboopathy/docker-gs-ping
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: DDGit
                    repoName: deenaboopathy/docker-gs-ping
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Sh
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    shell: Sh
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: account.harnessImage
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
